### ISSUE TITLE
Review from tomchor

### ISSUE THREAD

**Issue by malmans2** [hainegroup/oceanspy#109]
Here is the review by tomchor:
https://github.com/openjournals/joss-reviews/issues/1506#issuecomment-502532735

- [x] Statement of need: the target audience is very well stated, but in my opinion the problems the package aims to solve could be better stated. The paper itself has those problems/needs very well explained however.

- [x] Installation instructions: although the installation instructions are very clear, there is no explicitly stated list of dependencies. Instead the dependencies are implicitly listed in a conda install command.

- [x] Automated tests: there were no automated tests that I could find in the package.

- [x] The SciServer part in the tutorial was a bit confusing to me. This only a suggestion, but I think It would also be good to state the differences of working from within SciServer. (I know that there is a paragraph in the beginning on the docs trying to clarify the SciServer/standalone options, but I'm not sure if everyone is familiar with SciServer.) The flowchart, for example, could be one of the first things in the documentation (or at least in the getting started portion). Instead it is given a separate section with no context whatsoever.
Furthermore, the steps to start a SciServer didn't quite work for me. After clicking on compute, there was no option to Run Existing Notebook. I suspect they are outdated. It was very straightforward to figure out by myself the correct steps, but it would still be nice to have the correct instructions.

- [x] In some places (generally towards the ends of the tutorial sections) the comments tend to become scarce. An example are cells [7] through [9] in the Kogur case. A little explanation in these cases would benefit users.

- [x] Before cell [13] in [https://oceanspy.readthedocs.io/en/latest/Tutorial.html](the tutorial) the comment should say "while this syntax adds the new variable to od_drop"

- [x] I think it is really nice that in the paper (and also in the autogen docs) the calculations done by the compute module are mathematically defined. However, as a scientist, it would be nice to know which numerical scheme is used to perform those computations. I assume it is the default functionality of xarray, which uses specific numpy functions. A simple reference to the xarray function would suffice (to avoid having to go through code to figure it out).

Most of them are suggestions on how to improve the documentation. The reviewer was not able to find the automated tests, so we should add instructions somewhere else (currently they are in the contributing section, I think we should mention them in the installation section as well).

**Comment by ThomasHaine** [comment]
Sounds good to me. The other issues are easy to fix. Let me know if you need help!

**Comment by asiddi24** [comment]
Are we supposed to wait for both reviews to come before making changes ?

**Comment by malmans2** [comment]
I don't think so. Let's open a new pull request. I'll ask the editor if we can just merge it.

**Comment by renskegelderloos** [comment]
Sounds good! These are some good suggestions. Let me know if I can help/check edits etc.

Renske

On Jun 17, 2019, at 10:36 AM, Mattia Almansi <notifications@github.com<mailto:notifications@github.com>> wrote:


Here is the review by tomchor:
openjournals/joss-reviews#1506 (comment)<https://github.com/openjournals/joss-reviews/issues/1506#issuecomment-502532735>

  *    Statement of need: the target audience is very well stated, but in my opinion the problems the package aims to solve could be better stated. The paper itself has those problems/needs very well explained however.

  *    Installation instructions: although the installation instructions are very clear, there is no explicitly stated list of dependencies. Instead the dependencies are implicitly listed in a conda install command.

  *    Automated tests: there were no automated tests that I could find in the package.

  *    The SciServer part in the tutorial was a bit confusing to me. This only a suggestion, but I think It would also be good to state the differences of working from within SciServer. (I know that there is a paragraph in the beginning on the docs trying to clarify the SciServer/standalone options, but I'm not sure if everyone is familiar with SciServer.) The flowchart, for example, could be one of the first things in the documentation (or at least in the getting started portion). Instead it is given a separate section with no context whatsoever.
Furthermore, the steps to start a SciServer didn't quite work for me. After clicking on compute, there was no option to Run Existing Notebook. I suspect they are outdated. It was very straightforward to figure out by myself the correct steps, but it would still be nice to have the correct instructions.

  *    In some places (generally towards the ends of the tutorial sections) the comments tend to become scarce. An example are cells [7] through [9] in the Kogur case. A little explanation in these cases would benefit users.

  *    Before cell [13] in [https://oceanspy.readthedocs.io/en/latest/Tutorial.html](the tutorial) the comment should say "while this syntax adds the new variable to od_drop"

  *    I think it is really nice that in the paper (and also in the autogen docs) the calculations done by the compute module are mathematically defined. However, as a scientist, it would be nice to know which numerical scheme is used to perform those computations. I assume it is the default functionality of xarray, which uses specific numpy functions. A simple reference to the xarray function would suffice (to avoid having to go through code to figure it out).

Most of them are suggestions on how to improve the documentation. The reviewer was not able to find the automated tests, so we should add instructions somewhere else (currently they are in the contributing section, I think we should mention them in the installation section as well).

**Comment by asiddi24** [comment]
I have made a pull request addressing points 1, 2, 4 and 6. See if that works.

**Comment by malmans2** [comment]
Thanks! I'll be on it probably tomorrow. I think I can take care of the other points.

**Comment by malmans2** [comment]
The reviewer is making a good point [here](https://github.com/openjournals/joss-reviews/issues/1506#issuecomment-503770089). I suggest we add a note in the front page. This is what I'm thinking:
 "OceanSpy has been developed and tested using MITgcm output. However, it has been thought to be compatible with any ocean general circulation model. OceanSpy's structure allows to easily implement additional model-specific features, such as numerical schemes for vector calculus, budget closures, and equations of state. We are actively seeking feedback from different ocean model communities ([feedback submission](https://github.com/malmans2/oceanspy/issues))."
Thoughts? @ThomasHaine @renskegelderloos @asiddi24 @hooteoos-waltz

**Comment by ThomasHaine** [comment]
Yes, good point. I suggest this text:


"OceanSpy has been developed and tested using MITgcm output. However, it is designed to work with any (structured grid) ocean general circulation model. OceanSpy's architecture allows to easily implement model-specific features, such as different grids, numerical schemes for vector calculus, budget closures, and equations of state. We actively seek input and contributions from users of other ocean models (feedback submission<https://github.com/malmans2/oceanspy/issues>)."


On Jun 20, 2019, at 11:16 AM, Mattia Almansi <notifications@github.com<mailto:notifications@github.com>> wrote:


The reviewer is making a good point here<https://github.com/openjournals/joss-reviews/issues/1506#issuecomment-503770089>. I suggest we add a note in the front page. This is what I'm thinking:
"OceanSpy has been developed and tested using MITgcm output. However, it has been thought to be compatible with any ocean general circulation model. OceanSpy's structure allows to easily implement additional model-specific features, such as numerical schemes for vector calculus, budget closures, and equations of state. We are actively seeking feedback from different ocean model communities (feedback submission<https://github.com/malmans2/oceanspy/issues>)."
Thoughts? @ThomasHaine<https://github.com/ThomasHaine> @renskegelderloos<https://github.com/renskegelderloos> @asiddi24<https://github.com/asiddi24> @hooteoos-waltz<https://github.com/hooteoos-waltz>

**Comment by malmans2** [comment]
@ThomasHaine @renskegelderloos @asiddi24 @hooteoos-waltz 
Last task: the editor is asking to clarify which ocean models OceanSpy will work with in the [paper](https://github.com/openjournals/joss-papers/blob/joss.01506/joss.01506/10.21105.joss.01506.pdf).
I suggest we add the following line at the end of the Summary section:
"It is designed to work with structured grid ocean circulation models that use a finite volume approach to discretize in space."
What do you think?

**Comment by renskegelderloos** [comment]
Only C-grid, but otherwise ok.

On Jul 5, 2019, at 3:59 PM, Mattia Almansi <notifications@github.com<mailto:notifications@github.com>> wrote:


@ThomasHaine<https://github.com/ThomasHaine> @renskegelderloos<https://github.com/renskegelderloos> @asiddi24<https://github.com/asiddi24> @hooteoos-waltz<https://github.com/hooteoos-waltz>
Last task: the editor is asking to clarify which ocean models OceanSpy will work with in the paper<https://github.com/openjournals/joss-papers/blob/joss.01506/joss.01506/10.21105.joss.01506.pdf>.
I suggest we add the following line at the end of the Summary section:
"It is designed to work with structured grid ocean circulation models that use a finite volume approach to discretize in space."
What do you think?

**Comment by malmans2** [comment]
Right, let's be more specific. I'll add the Arakawa citation then. So it would be:

It is designed to work with structured C-grid ([Arakawa and Lamb, 1977](https://www.sciencedirect.com/science/article/pii/B9780124608177500094)) ocean circulation models that use a finite volume approach to discretize in space.

If it works for @ThomasHaine, I'll create the doi for the paper.

**Comment by ThomasHaine** [comment]
Is the finite volume part necessary?  Presumably, it would be relatively straightforward to adjust for A or B grid models in future?



On Jul 5, 2019, at 4:20 PM, Mattia Almansi <notifications@github.com<mailto:notifications@github.com>> wrote:


Right, let's be more specific. I'll add the Arakawa citation then. So it would be:

It is designed to work with structured C-grid (Arakawa and Lamb, 1977<https://www.sciencedirect.com/science/article/pii/B9780124608177500094>) ocean circulation models that use a finite volume approach to discretize in space.

If it works for @ThomasHaine<https://github.com/ThomasHaine>, I'll create the doi for the paper.

**Comment by malmans2** [comment]
I originally thought to add the finite volume bit because it tells about the numerics currently used in compute, and it includes most of the GCM that use C-grid. Now I'm thinking that maybe we could just add a separate section in the paper (e.g., Model compatibility), where we include the same sentences we have on the front page with a reference to the the MITgcm:
### Model compatibility
OceanSpy has been developed and tested using output of the Massachusets Institute of Technology General Circulation Model (MITgcm; [Marshall et al. 1997](https://agupubs.onlinelibrary.wiley.com/doi/abs/10.1029/96JC02775)). However, it is designed to work with any (structured grid) ocean general circulation model. OceanSpy’s architecture allows to easily implement model-specific features, such as different grids, numerical schemes for vector calculus, budget closures, and equations of state.

**Comment by renskegelderloos** [comment]
That sounds great!
Renske

On Jul 5, 2019, at 4:58 PM, Mattia Almansi <notifications@github.com<mailto:notifications@github.com>> wrote:


I originally thought to add the finite volume bit because it tells about the numerics currently used in compute, and it includes most of the GCM that use C-grid. Now I'm thinking that maybe we could just add a separate section in the paper (e.g., Model compatibility), where we include the same sentences we have on the front page with a reference to the the MITgcm:

Model compatibility

OceanSpy has been developed and tested using output of the Massachusets Institute of Technology General Circulation Model (MITgcm; Marshall et al. 1997<https://agupubs.onlinelibrary.wiley.com/doi/abs/10.1029/96JC02775>). However, it is designed to work with any (structured grid) ocean general circulation model. OceanSpy’s architecture allows to easily implement model-specific features, such as different grids, numerical schemes for vector calculus, budget closures, and equations of state.

**Comment by ThomasHaine** [comment]
Looks good to me too!


On Jul 6, 2019, at 10:39 AM, renskegelderloos <notifications@github.com<mailto:notifications@github.com>> wrote:

That sounds great!
Renske

On Jul 5, 2019, at 4:58 PM, Mattia Almansi <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


I originally thought to add the finite volume bit because it tells about the numerics currently used in compute, and it includes most of the GCM that use C-grid. Now I'm thinking that maybe we could just add a separate section in the paper (e.g., Model compatibility), where we include the same sentences we have on the front page with a reference to the the MITgcm:

Model compatibility

OceanSpy has been developed and tested using output of the Massachusets Institute of Technology General Circulation Model (MITgcm; Marshall et al. 1997<https://agupubs.onlinelibrary.wiley.com/doi/abs/10.1029/96JC02775>). However, it is designed to work with any (structured grid) ocean general circulation model. OceanSpy’s architecture allows to easily implement model-specific features, such as different grids, numerical schemes for vector calculus, budget closures, and equations of state.
