### ISSUE TITLE
File not closed

### ISSUE THREAD

**Issue by hooteoos-waltz** [hainegroup/oceanspy#19]
In the utils.py source code, line 258 the file is not closed. And therefore 
I cannot delete the temporary file that I generated using thetutorial:
path = './tmp/checkpoint'
ospy.utils.save_ds_info(ds_cut, info_cut, path)
ds_cut, info_cut = ospy.utils.open_ds_info(path)

**Comment by malmans2** [comment]
Good catch!
This and #20 should be fixed now. Can you test my branch?
To install it you have to do: pip install git+https://github.com/malmans2/oceanspy.git@path_bugs
I'll wait your OK to merge my pull request, and close your issues.
Thanks!

**Comment by hooteoos-waltz** [comment]
Hey!
The code looks good, but still the tmp file can't be deleted by rm -r or by emptying the content, unless I kill the kernel and reconnect again. But it's not a big issue, so feel free to merge the pull request.

**Comment by malmans2** [comment]
Let's fix it! If we start accumulating issues since the very beginning we'll get in trouble.
1) are you sure that you installed the ``path_bugs`` branch? Do ``pip uninstall oceanspy`` first, then ``pip install git+https://github.com/malmans2/oceanspy.git@path_bugs``. Does it work now?
2) are you trying to delete files or repositories? Try to delete the actual files, not the repository. Does it work?
3) if deleting files work but repositories doesn't, what is the error? It might be a security policy of SciServer. Try ``rm -fr``. Does it work? (Please send me the error you get even if ``rm -fr`` works).

**Comment by hooteoos-waltz** [comment]
I did install the path_bugs. 
I try to delete the "tmp" file and its content. 
Forcing to remove it in step 3 would give me these errors:
rm: cannot remove 'tmp/.nfs0000000500747daa00000007': Device or resource busy
rm: cannot remove 'tmp/.nfs000000050077414a00000008': Device or resource busy

**Comment by malmans2** [comment]
Reminder to myself: double check this issue and add progress bar when saving!
