### ISSUE TITLE
Ertel PV shape

### ISSUE THREAD

**Issue by ThomasHaine** [hainegroup/oceanspy#54]
* OceanSpy version:

Are the Ertel PV dimensions (and chunksize) wrong?

I get:

S          (time, Z, Y, X) float64 dask.array<shape=(2, 216, 878, 958), chunksize=(2, 216, 878, 958)>
    Temp       (time, Z, Y, X) float64 dask.array<shape=(2, 216, 878, 958), chunksize=(2, 216, 878, 958)>
    U          (time, Z, Y, Xp1) float64 dask.array<shape=(2, 216, 878, 959), chunksize=(2, 216, 878, 959)>
    V          (time, Z, Yp1, X) float64 dask.array<shape=(2, 216, 879, 958), chunksize=(2, 216, 879, 958)>
    W          (time, Zl, Y, X) float64 dask.array<shape=(2, 216, 878, 958), chunksize=(2, 216, 878, 958)>
    Sigma0     (time, Z, Y, X) float64 dask.array<shape=(2, 216, 878, 958), chunksize=(2, 216, 878, 958)>
    EKE        (time, Z, Y, X) float64 dask.array<shape=(2, 216, 878, 958), chunksize=(2, 216, 878, 958)>
    Ertel_PV   (Y, X, time, Z) float64 dask.array<shape=(878, 958, 2, 216), chunksize=(1, 1, 2, 1)>

which confuses me.

**Comment by ThomasHaine** [comment]
Ditto Okubo-Weiss

 Okubo_Weiss  (Y, X, time, Z) float64 dask.array<shape=(878, 958, 2, 216), chunksize=(1, 1, 2, 216)>

**Comment by ThomasHaine** [comment]
And N2 and momVort3

**Comment by malmans2** [comment]
It shouldn't matter the location of the dimensions because we always refer to the dimension name, not index. Indeed, with xarray you can multiply arrays with different dimensions without having to reshape, add dimensions, ... In practice, my guess is that having variables with dimensions in different orders will slow down the computation at some point because arrays need to be transposed. 

Regarding the chunk size, that's bad and it happens when I'm combining variables coming from different grids. 

I'm working on a new push with (should be ready soon): 
1) Correct shape of all variables I noticed with wrong shape
2) All variables in an oceandataset will have the same chunk size (ok for now, probably I should also do it in the functions as well, before the variables are merged in the oceandataset)
3) Add a switch for Ertel PV so you can neglect the horizontal components of vorticity
4) Add a function to compute cell volumes

Please keep reporting inconsistencies, and let me know if any output doesn't make sense. The way to fix problem 1) is just change the order of operations. Hopefully I didn't messed up any operation.

**Comment by malmans2** [comment]
Pushed! git pull to update your oceanspy, and you can find the documentation in OceanSpy_Tutorials.

BTW, you were right. Functions like Ertel_PV will fail if you need to compute gradients, and there aren't enough grid points. I'll add some error message!

**Comment by ThomasHaine** [comment]
@malmans2 how, exactly, do I "git pull"?  pip install -e oceanspy/ doesn't seem to update the oceanspy module. How do I tell which module version I have installed?  [Sorry for the github ignorance!]

**Comment by malmans2** [comment]
`pip install -e oceanspy/` installed the code that is in `oceanspy/` (basically, it executes `oceanspy/setup.py`. It doesn't matter the name of the folder, it could be `myOcEaNsPy/`). From now on it will keep track of changes in the folder installed. The folder is also connected to git: To update oceanspy, `cd oceanspy/`, and `git pull` from there. Git will print on terminal any update, or it will tell you if the repository is already uptodate. If you updated the right oceanspy folder, which is the one installed using `pip install -e`, that's it. You only need to restart the kernel of your notebook to load any change.

You can quickly check if you have the new version by running the following commands:
```python
import oceanspy as ospy
help(ospy.compute.volume_cells)
```   
If it works, you're all set. If it doesn't work, you didn't pull oceanspy, or you pulled oceanspy in a repository that is not installed. In that case, uninstall oceanspy first, then install the right repository:
```bash
$ pip uninstall oceanspy
$ pip install -e oceanspy/
```
Then restart the kernel of the notebook, and you should be all set.

**Comment by ThomasHaine** [comment]
from my oceanspy directory I get:

[idies@5a704fd6d6c4 oceanspy]$ pwd
/home/idies/workspace/Storage/Thomas.Haine/persistent/OceanSpy_dev/oceanspy
[idies@5a704fd6d6c4 oceanspy]$ git pull
fatal: Not a git repository (or any parent up to mount point /home/idies/workspace/Storage/Thomas.Haine/persistent)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

And if I pip uninstall oceanspy then pip install -e oceanspy/ and restart the kernel, it hasn't updated.

**Comment by malmans2** [comment]
For some reason your oceanspy directory is not connected to git. My guess is that you copied it without copying the git hidden files. You need do clone the directory again:
```bash
$ git clone --single-branch --branch oceandataset https://github.com/malmans2/oceanspy.git
```
Now check if it's connected to git
```bash
$ cd oceanspy
$ git pull
```
It should be up to date. If you are still in the oceanspy repo, go back and install:
```bash
$ cd ..
$ pip install -e oceanspy/
```

**Comment by ThomasHaine** [comment]
Thanks!  That works.

**Comment by ThomasHaine** [comment]
@malmans2 I think we need a 5th volume field for (e.g. MomVort3) cell corner points. I.e. volumes over (Xp1,Yp1,Z)

**Comment by ThomasHaine** [comment]
[Cosmetic suggestion:] Add print statement "Computing cell volumes" (or similar) for merge_volume_cells() to be consistent with other merge compute functions.
