### ISSUE TITLE
xgcm v0.2.0

### ISSUE THREAD

**Issue by renskegelderloos** [hainegroup/oceanspy#66]
* OceanSpy version: 0.0.11

### Description
I tried to do a cutout of the model domain on my local computer. It did not work because the grid was not properly loaded. It turns out the problem was that oceanspy is not currently compatible with xgcm v0.2.0. When I went back to 0.1.0 it worked fine.

**Comment by malmans2** [comment]
Can you please share the error and/or the cutout parameters that generated the error?

**Comment by renskegelderloos** [comment]
See #65 (Ignore the curvilinear grid part; it turned out that was not the problem)

**Comment by malmans2** [comment]
OK, the grid object changed a little in version 0.2. 
`od._grid.axes['X'].coords['outer'].name` now needs to be replaced by `od._grid.axes['X'].coords['outer']`.
Since we don't have a stable release yet, I would just support xgcm0.2. We can also replace some of OceanSpy's functions with xgcm new features (autogenerate for midp dimensions and we can now use the coords parameter in `xgcm.Grid` without having to add comodo attributes).
