### ISSUE TITLE
compute loses attributes

### ISSUE THREAD

**Issue by ThomasHaine** [hainegroup/oceanspy#78]
Calling compute to add a new variable to a dataset loses the attributes (e.g. units) of the coordinate variables. This seems like an undesirable default.

`import oceanspy          as ospy`
`od = ospy.open_oceandataset.from_catalog('get_started')`
`print(od.dataset['X'])`
`od2 = od.compute.potential_density_anomaly()`
`print(od2.dataset['X'])`

**Comment by asiddi24** [comment]
One fix around that is to use ospy.compute instead of od.compute. Using ospy.compute retains the global attributes of the dataset for all functions. If you try this

`import oceanspy as ospy`
`od = ospy.open_oceandataset.from_catalog('get_started')`
`print(od.dataset['X'])`
`od2 = ospy.compute.potential_density_anomaly(od)`
`print(od2['X'])`

It will return the attributes for the coordinate variables as well. 
Although, yeah, we'll have to correct for using it the other way too.

**Comment by malmans2** [comment]
@asiddi24 you're right! Do you want to review this PR #79 ?
